const { ipcRenderer } = require('electron')
const {
    START_NOTIFICATION_SERVICE,
    NOTIFICATION_SERVICE_STARTED,
    NOTIFICATION_SERVICE_ERROR,
    NOTIFICATION_RECEIVED,
    TOKEN_UPDATED,
} = require('electron-push-receiver/src/constants')

window.ipcRenderer = ipcRenderer

window.START_NOTIFICATION_SERVICE = START_NOTIFICATION_SERVICE;
window.NOTIFICATION_SERVICE_STARTED = NOTIFICATION_SERVICE_STARTED;
window.NOTIFICATION_SERVICE_ERROR = NOTIFICATION_SERVICE_ERROR;
window.NOTIFICATION_RECEIVED = NOTIFICATION_RECEIVED;
window.TOKEN_UPDATED = TOKEN_UPDATED;